title: Hassan Ishtiaq's Homepage
page-top-title: Hassan Ishtiaq
top-section-bg-text: Hardware & Electronic Design
home-subtitle: Hassan Ishtiaq
copyright-text: '&copy; Hassan Ishtiaq 2026. All Rights Reserved. Last Updated: July 2026.'
